# Generated by Django 4.2.20 on 2025-07-15 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_userprofile_courseware_userprofile_education_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='courseware',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='education_level',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='language',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='mailing_address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='year_of_birth',
        ),
    ]
