# Generated by Django 4.2.20 on 2025-07-15 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_remove_userprofile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='franchise',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Franchise',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
