# Generated by Django 4.2.20 on 2025-07-15 09:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0014_userfranchise'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserFranchise',
            new_name='UserProfile',
        ),
    ]
