# Generated by Django 4.2.20 on 2025-07-15 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_profile_delete_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
