# Generated by Django 4.2.20 on 2025-07-17 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0018_userfranchise'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfranchise',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userfranchise',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='FeeDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_installments', models.PositiveIntegerField()),
                ('paid_installments', models.PositiveIntegerField(default=0)),
                ('user_franchise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='application.userfranchise')),
            ],
        ),
    ]
