# Generated by Django 4.2.20 on 2025-08-18 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='franchise',
            name='address',
        ),
    ]
