# Generated by Django 4.2.20 on 2025-08-18 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_remove_franchise_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchise',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='franchise',
            name='registration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
