# Generated by Django 4.2.20 on 2025-08-20 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_franchise_location_franchise_registration_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Franchise',
        ),
    ]
