# Generated by Django 4.2.20 on 2025-07-15 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_userprofile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='courseware',
            field=models.CharField(blank=True, default='course.xml', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='education_level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mailing_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='year_of_birth',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
