# Generated by Django 4.2.20 on 2025-08-22 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_usercourseenrollment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCourseEnrollment',
        ),
    ]
