# Generated by Django 4.2.20 on 2025-09-01 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_delete_usercourseenrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=255, unique=True)),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('franchise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.franchise')),
            ],
        ),
    ]
