# Generated by Django 4.2.20 on 2025-09-01 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_coursefee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseFee',
        ),
    ]
