# Generated by Django 4.2.20 on 2025-07-15 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_userprofile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
    ]
