# Generated by Django 4.2.20 on 2025-09-01 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0029_alter_historicalcourseoverview_options'),
        ('application', '0011_coursefee'),
    ]

    operations = [
        migrations.CreateModel(
            name='FranchiseCourseDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='course_overviews.courseoverview')),
                ('franchise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_discounts', to='application.franchise')),
            ],
            options={
                'unique_together': {('franchise', 'course')},
            },
        ),
    ]
