# Generated by Django 4.2.20 on 2025-07-15 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0012_remove_userprofile_franchise_remove_userprofile_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=255)),
                ('joining_date', models.DateField()),
            ],
        ),
    ]
