# Generated by Django 4.2.20 on 2025-09-02 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeInstallment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_no', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('paid', models.BooleanField(default=False)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='application.batch')),
            ],
            options={
                'unique_together': {('batch', 'installment_no')},
            },
        ),
    ]
