# Generated by Django 4.2.20 on 2025-09-02 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_feeinstallment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeeInstallment',
        ),
    ]
