# Generated by Django 4.2.20 on 2025-09-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_batchfeemanagement_feeinstallment'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchfeemanagement',
            name='period_type',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('daily', 'Daily')], default='monthly', max_length=10),
        ),
    ]
