# Generated by Django 4.2.20 on 2025-09-03 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0017_batchfeemanagement_period_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feeinstallment',
            name='fee_management',
        ),
        migrations.DeleteModel(
            name='BatchFeeManagement',
        ),
        migrations.DeleteModel(
            name='FeeInstallment',
        ),
    ]
