# Generated by Django 4.2.20 on 2025-09-03 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0018_remove_feeinstallment_fee_management_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfranchise',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.batch'),
        ),
    ]
