# Generated by Django 4.2.20 on 2025-09-03 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0019_userfranchise_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchFeeManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('period_type', models.CharField(choices=[('monthly', 'Monthly'), ('daily', 'Daily')], default='monthly', max_length=10)),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fee_management', to='application.batch')),
            ],
        ),
        migrations.RemoveField(
            model_name='userfranchise',
            name='batch',
        ),
        migrations.CreateModel(
            name='FeeInstallment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('duration_months', models.PositiveIntegerField()),
                ('installment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fee_management', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='application.batchfeemanagement')),
            ],
        ),
    ]
