# Generated by Django 4.2.20 on 2025-09-03 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0020_batchfeemanagement_remove_userfranchise_batch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchfeemanagement',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='coursefee',
            name='course',
        ),
        migrations.RemoveField(
            model_name='feeinstallment',
            name='fee_management',
        ),
        migrations.AlterUniqueTogether(
            name='franchisecoursediscount',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='franchisecoursediscount',
            name='course',
        ),
        migrations.RemoveField(
            model_name='franchisecoursediscount',
            name='franchise',
        ),
        migrations.DeleteModel(
            name='Batch',
        ),
        migrations.DeleteModel(
            name='BatchFeeManagement',
        ),
        migrations.DeleteModel(
            name='CourseFee',
        ),
        migrations.DeleteModel(
            name='FeeInstallment',
        ),
        migrations.DeleteModel(
            name='FranchiseCourseDiscount',
        ),
    ]
