# Generated by Django 4.2.20 on 2025-07-17 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0020_feestructure_installment_student_studentfee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFranchise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='installment',
            name='fee_structure',
        ),
        migrations.RemoveField(
            model_name='student',
            name='franchise',
        ),
        migrations.RemoveField(
            model_name='studentfee',
            name='fee_structure',
        ),
        migrations.RemoveField(
            model_name='studentfee',
            name='student',
        ),
        migrations.RemoveField(
            model_name='franchise',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='franchise',
            name='email',
        ),
        migrations.AlterField(
            model_name='franchise',
            name='joining_date',
            field=models.DateField(),
        ),
        migrations.DeleteModel(
            name='FeeStructure',
        ),
        migrations.DeleteModel(
            name='Installment',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='StudentFee',
        ),
        migrations.AddField(
            model_name='userfranchise',
            name='franchise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.franchise'),
        ),
        migrations.AddField(
            model_name='userfranchise',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
