# Generated by Django 4.2.20 on 2025-09-03 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0029_alter_historicalcourseoverview_options'),
        ('application', '0021_remove_batchfeemanagement_batch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=50, unique=True)),
                ('fees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='course_overviews.courseoverview')),
                ('franchise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='application.franchise')),
            ],
        ),
    ]
