# Generated by Django 4.2.20 on 2025-07-18 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0021_userfranchise_remove_installment_fee_structure_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FranchiseStudentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('fees', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('user_franchise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='application.userfranchise')),
            ],
        ),
    ]
