# Generated by Django 4.2.20 on 2025-07-18 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0022_franchisestudentdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FranchiseStudentDetails',
        ),
    ]
