# Generated by Django 4.2.20 on 2025-09-03 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0023_userfranchise_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchFeeManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('installment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('repayment_period_days', models.PositiveIntegerField(default=30)),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fee_management', to='application.batch')),
            ],
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending', max_length=10)),
                ('payment_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentFeeManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('batch_fee_management', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.batchfeemanagement')),
                ('user_franchise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fee_management', to='application.userfranchise')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('installment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='application.installment')),
            ],
        ),
        migrations.AddField(
            model_name='installment',
            name='student_fee_management',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='application.studentfeemanagement'),
        ),
    ]
