# Generated by Django 4.2.20 on 2025-09-03 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0024_batchfeemanagement_installment_studentfeemanagement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallmentTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('repayment_period_days', models.PositiveIntegerField()),
                ('batch_fee_management', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment_templates', to='application.batchfeemanagement')),
            ],
        ),
    ]
