# Generated by Django 4.2.20 on 2025-07-21 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0024_franchisestudentdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='franchisestudentdetails',
            name='fees',
        ),
    ]
