# Generated by Django 4.2.20 on 2025-09-09 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0025_installmenttemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='repayment_period_days',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
