# Generated by Django 4.2.20 on 2025-07-21 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0026_studentfeedetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentfeedetail',
            name='paid_installments',
        ),
        migrations.RemoveField(
            model_name='studentfeedetail',
            name='student',
        ),
        migrations.AddField(
            model_name='studentfeedetail',
            name='installments_paid',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='studentfeedetail',
            name='user_franchise',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_detail', to='application.userfranchise'),
        ),
        migrations.AlterField(
            model_name='studentfeedetail',
            name='total_fees',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='studentfeedetail',
            name='total_installments',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
