# Generated by Django 4.2.20 on 2025-07-21 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0027_remove_studentfeedetail_paid_installments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfeedetail',
            name='fees_paid',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
